package com.github.adminfaces.addon.scaffold.model;

public enum ComponentTypeEnum {
	INPUT_TEXT, TEXT_AREA, INPUT_NUMBER, SPINNER,
	SELECT_ONE_MENU, SELECT_ONE_RADIO,
	SELECT_MANY_MENU, SELECT_MANY_CHECKBOX,
	CHECKBOXMENU, AUTOCOMPLETE, INPUT_SWITCH,
	CALENDAR, PASSWORD;
}
